Algoritmo "media"

Var
nota_um,nota_dois,nota_tres, nota_quatro : real


Inicio
escreva("Digite a nota do 1° Bimestre: ")
leia(nota_um)
escreva("Digite a nota do 2° Bimestre: ")
leia(nota_dois)
escreva("Digite a nota do 3° Bimestre: ")
leia(nota_tres)
escreva("Digite a nota do 4° Bimestre: ")
leia(nota_quatro)
escreva("A média do aluno é : ",((nota_um+nota_dois+nota_tres+ nota_quatro)/4)

Fimalgoritmo